---
- name: Run ise_audit__config_changes
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - cisco.ise
    - community.general
  vars_files:
    - vars.example.yml
  roles:
    - role: ise_audit__config_changes
