galaxy_info:
  author: Dewain Smith
  description: Find and/or delete VMware vSphere VM snapshots at scale.
  company: ""
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions: ["all"]
    - name: Ubuntu
      versions: ["all"]
  galaxy_tags: ["vmware", "vsphere", "snapshots", "automation"]

dependencies: []
